In [5]:
# Librerias necesarias
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 


# Numpy

In [2]:
b = np.array(range(11,1,-1))
a = np.arange(11,1,-1)
print a, type(a), b

[11 10  9  8  7  6  5  4  3  2] <type 'numpy.ndarray'> [11 10  9  8  7  6  5  4  3  2]


In [23]:
for indice,contenido in enumerate(a):
    pass

print n
print m

9
2


In [27]:
x = np.arange(-2, 3)
x

array([-2, -1,  0,  1,  2])

# RANDOM

In [14]:
print np.random.choice(5)
random_array= np.random.choice(5,100)
print random_array


2
[2 3 3 2 1 4 0 2 1 2 2 1 1 0 4 4 4 2 4 4 0 0 4 2 2 3 2 3 0 1 3 3 0 2 3 1 3
 1 3 2 2 4 1 4 2 1 3 0 2 4 1 3 4 2 2 0 3 0 2 2 1 1 3 1 3 1 2 3 0 0 4 4 1 3
 2 3 2 3 1 2 2 2 2 2 4 1 4 0 3 0 3 2 3 0 3 0 1 1 4 1]


In [2]:
plt.hist(random_array)

NameError: name 'plt' is not defined

In [14]:
valores = np.arange(20,0,-1)
for i in valores:
    if valores[i-1] % 5 == 0:
        valores[i-1]= 0
        
print "valores: ", valores
print "valores: ", (np.flatnonzero(valores)) # Lista de posiciones del vector "valores" que no son cero

valores = 4*valores

np.random.choice(valores,5)

valores:  [ 0 19 18 17 16  0 14 13 12 11  0  9  8  7  6  0  4  3  2  1]
valores:  [ 1  2  3  4  6  7  8  9 11 12 13 14 16 17 18 19]


array([ 8, 68, 68, 32,  8])

In [1]:
a = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.reshape(a, -1)# b = np.reshape(a, a.shape[0]*a.shape[1])
print a, a.shape
print b, b.shape


NameError: name 'np' is not defined

In [95]:
v1 = np.arange(20)
v2 = v1**2
random_array= np.random.choice(5,100)

# print v1,"\n" ,v2
print random_array
print random_array[:1]
idx_random_array_sorted = np.argsort(random_array)
print np.take(random_array , idx_random_array_sorted)

#for i,idx in enumerate(idx_random_array_sorted):
    #print random_array[idx]




[3 0 4 1 0 3 2 2 4 0 3 1 4 2 0 3 2 2 3 3 2 1 1 4 1 3 2 3 4 2 0 3 0 3 1 0 1
 2 3 1 4 2 0 1 1 4 4 2 3 2 0 2 1 0 0 0 4 4 3 4 1 3 1 0 3 0 1 2 0 1 1 1 1 3
 1 4 1 0 1 1 1 2 2 0 0 1 2 3 0 2 0 2 0 3 1 1 4 1 4 0]
[3]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4]


** bincount : Para contar valores repetidos**

In [44]:
x = np.array([1,1,1,2,2,2,5,25,1,1])
y = np.bincount(x)
ii = np.flatnonzero(y)

print y
print ii

[0 5 3 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[ 1  2  5 25]


** Unique **


In [67]:
x = np.array([1,1,1,2,2,2,5,25,1,1])
y , frecuency = np.unique(x , return_counts= True) 
print frecuency
most_repeated = np.amax(frecuency)
others_most_repeated = frecuency[frecuency == most_repeated]
print others_most_repeated
print y

def predictingClass(vectorOfClasses)
    """ Introduce an array of the classes and
    return an array with the class predict"""
    theClasses , frecuencyOfClasses = np.unique(vectorOfClasses , return_counts= True)    
    
    
def someClassesWin(theClasses , frecuencyOfClasses)
     iOfFocMax = np.argmax(frecuencyOfClasses)
     listOfTheMostRepeatedFrecuency = frecuencyOfClasses[iOfFocMax] == frecuencyOfClasses
    return theClasses[listOfTheMostRepeatedFrecuency]
    ## xx , frecuency = np.unique(frecuencyOfClasses)


SyntaxError: invalid syntax (<ipython-input-67-340d1ad2962c>, line 9)

In [90]:
frecuencyOfClasses = np.array([3,4,4,5,5])
theClasses = np.arange(5)
print theClasses , frecuencyOfClasses
iOfFocMax = np.argmax(frecuencyOfClasses)
listOfTheMostRepeatedFrecuency = frecuencyOfClasses[iOfFocMax] == frecuencyOfClasses
print theClasses[listOfTheMostRepeatedFrecuency]





def someClassesWin(theClasses , frecuencyOfClasses):
    iOfFocMax = np.argmax(frecuencyOfClasses)
    listOfTheMostRepeatedFrecuency = frecuencyOfClasses[iOfFocMax] == frecuencyOfClasses
    return theClasses[listOfTheMostRepeatedFrecuency]


[0 1 2 3 4] [3 4 4 5 5]
[3 4]


In [96]:
print someClassesWin(theClasses , frecuencyOfClasses)
print np.amin(someClassesWin(theClasses,frecuencyOfClasses))

[3 4]
3


In [1]:
x = np.array([1,1,1,2,2,2,5,25,1,1])
indices = np.array([1,4,7])
print x[indices]

NameError: name 'np' is not defined

In [9]:
v1 = np.arange(10)
print v1, 2 - v1



[0 1 2 3 4 5 6 7 8 9] [ 2  1  0 -1 -2 -3 -4 -5 -6 -7]
